-- Generated users + credentials for every tenant (run: mysql -u myroot < this file)
USE sfa_central;
INSERT INTO app_user (username,password,tenant_id,enabled,name,email,role) VALUES ('demo_admin','$2y$10$ccA0oiFZz0DJnE0m0rJ6XOjIn/5YmAjeUnzoZy3cN30Z5DPkrpSuW','demo',1,'Demo Admin','admin@demo.com','ADMIN') ON DUPLICATE KEY UPDATE password=VALUES(password),tenant_id=VALUES(tenant_id),name=VALUES(name),email=VALUES(email),role=VALUES(role),enabled=1;
INSERT INTO app_user (username,password,tenant_id,enabled,name,email,role) VALUES ('demo_mgr','$2y$10$IP3kp0E32b.AwVNv4fBVLu84986OxOzxNjdkr9QFfa1rW8uUiNEoC','demo',1,'Demo Manager','mgr@demo.com','MANAGER') ON DUPLICATE KEY UPDATE password=VALUES(password),tenant_id=VALUES(tenant_id),name=VALUES(name),email=VALUES(email),role=VALUES(role),enabled=1;
INSERT INTO app_user (username,password,tenant_id,enabled,name,email,role) VALUES ('demo_rep1','$2y$10$JdAL/H2t09CBVSshYtQ/k.ZGeF/1WfB4v21dcebrn2FbS799MY5x.','demo',1,'Demo Rep 1','rep1@demo.com','USER') ON DUPLICATE KEY UPDATE password=VALUES(password),tenant_id=VALUES(tenant_id),name=VALUES(name),email=VALUES(email),role=VALUES(role),enabled=1;
INSERT INTO app_user (username,password,tenant_id,enabled,name,email,role) VALUES ('demo_rep2','$2y$10$5SBTY7TiP6CPOmVs1N.NGOe6/dbiS7wldWocNMeTbXjvqHzrV8DQe','demo',1,'Demo Rep 2','rep2@demo.com','USER') ON DUPLICATE KEY UPDATE password=VALUES(password),tenant_id=VALUES(tenant_id),name=VALUES(name),email=VALUES(email),role=VALUES(role),enabled=1;
INSERT INTO app_user (username,password,tenant_id,enabled,name,email,role) VALUES ('acme_admin','$2y$10$O5etyjFGYtOcjq6MAEOnaOC5tequk3RT.pG5b54j7WfLvzp7YL5FS','acme',1,'Acme Admin','admin@acme.com','ADMIN') ON DUPLICATE KEY UPDATE password=VALUES(password),tenant_id=VALUES(tenant_id),name=VALUES(name),email=VALUES(email),role=VALUES(role),enabled=1;
INSERT INTO app_user (username,password,tenant_id,enabled,name,email,role) VALUES ('acme_mgr','$2y$10$ifsXaMEXrMYFnXqjE22lROKmYpZH4p2E5thLfL8SqpM4jIHxuIZDG','acme',1,'Acme Manager','mgr@acme.com','MANAGER') ON DUPLICATE KEY UPDATE password=VALUES(password),tenant_id=VALUES(tenant_id),name=VALUES(name),email=VALUES(email),role=VALUES(role),enabled=1;
INSERT INTO app_user (username,password,tenant_id,enabled,name,email,role) VALUES ('acme_rep1','$2y$10$tYOIeXY8NfbImT6QZsBBo.mjKkIa/tU5Sx5yOcYAX72dOVksRT7zG','acme',1,'Acme Rep 1','rep1@acme.com','USER') ON DUPLICATE KEY UPDATE password=VALUES(password),tenant_id=VALUES(tenant_id),name=VALUES(name),email=VALUES(email),role=VALUES(role),enabled=1;
INSERT INTO app_user (username,password,tenant_id,enabled,name,email,role) VALUES ('acme_rep2','$2y$10$IkGBQIPzyloCvNzyt6VNFeaMutvi.9VmMnYCDpoImSlFbH.D/J7U6','acme',1,'Acme Rep 2','rep2@acme.com','USER') ON DUPLICATE KEY UPDATE password=VALUES(password),tenant_id=VALUES(tenant_id),name=VALUES(name),email=VALUES(email),role=VALUES(role),enabled=1;
INSERT INTO app_user (username,password,tenant_id,enabled,name,email,role) VALUES ('globex_admin','$2y$10$Rjv6mDXd4adYEPawAWFVU.9wmd4VlkKGpJiMMr2cIGhzTsP.ur1E.','globex',1,'Globex Admin','admin@globex.com','ADMIN') ON DUPLICATE KEY UPDATE password=VALUES(password),tenant_id=VALUES(tenant_id),name=VALUES(name),email=VALUES(email),role=VALUES(role),enabled=1;
INSERT INTO app_user (username,password,tenant_id,enabled,name,email,role) VALUES ('globex_mgr','$2y$10$rRo5sC0lK9APVpz2K0r/o.lFdN/3uJ.07qdsudzJo44XDGZhDiOD2','globex',1,'Globex Manager','mgr@globex.com','MANAGER') ON DUPLICATE KEY UPDATE password=VALUES(password),tenant_id=VALUES(tenant_id),name=VALUES(name),email=VALUES(email),role=VALUES(role),enabled=1;
INSERT INTO app_user (username,password,tenant_id,enabled,name,email,role) VALUES ('globex_rep1','$2y$10$C3AlneoQO10Go1XtuZ638uwSjvnXTm1uPIGZ14nqjIIDD7RTUkv7m','globex',1,'Globex Rep 1','rep1@globex.com','USER') ON DUPLICATE KEY UPDATE password=VALUES(password),tenant_id=VALUES(tenant_id),name=VALUES(name),email=VALUES(email),role=VALUES(role),enabled=1;
INSERT INTO app_user (username,password,tenant_id,enabled,name,email,role) VALUES ('globex_rep2','$2y$10$pHBQgWR/CU8chqQ0.PpiPO2we5je29Qw43wfc1c4k0zw8JeAPt0zu','globex',1,'Globex Rep 2','rep2@globex.com','USER') ON DUPLICATE KEY UPDATE password=VALUES(password),tenant_id=VALUES(tenant_id),name=VALUES(name),email=VALUES(email),role=VALUES(role),enabled=1;
INSERT INTO app_user (username,password,tenant_id,enabled,name,email,role) VALUES ('initech_admin','$2y$10$S0Oojbuv4jkqK5R4RjX0fuHZ8PQJ//JeiuRAFwa2VhJiJoBf5xyfO','initech',1,'Initech Admin','admin@initech.com','ADMIN') ON DUPLICATE KEY UPDATE password=VALUES(password),tenant_id=VALUES(tenant_id),name=VALUES(name),email=VALUES(email),role=VALUES(role),enabled=1;
INSERT INTO app_user (username,password,tenant_id,enabled,name,email,role) VALUES ('initech_mgr','$2y$10$TytGh1zrK1leFggpoRsN0OtT77F2VZeFAeNw4znZlDcLsJQHuge6q','initech',1,'Initech Manager','mgr@initech.com','MANAGER') ON DUPLICATE KEY UPDATE password=VALUES(password),tenant_id=VALUES(tenant_id),name=VALUES(name),email=VALUES(email),role=VALUES(role),enabled=1;
INSERT INTO app_user (username,password,tenant_id,enabled,name,email,role) VALUES ('initech_rep1','$2y$10$YkUtEQpSE.g55BTih9pdFeFp68G.uvpZlLNpvZ8mvNaFEvWEeoehi','initech',1,'Initech Rep 1','rep1@initech.com','USER') ON DUPLICATE KEY UPDATE password=VALUES(password),tenant_id=VALUES(tenant_id),name=VALUES(name),email=VALUES(email),role=VALUES(role),enabled=1;
INSERT INTO app_user (username,password,tenant_id,enabled,name,email,role) VALUES ('initech_rep2','$2y$10$1X.9qQssp7vyW4MRDDOZauNSiunEDCbUFSihfFnLnAvSj7RC0fPOa','initech',1,'Initech Rep 2','rep2@initech.com','USER') ON DUPLICATE KEY UPDATE password=VALUES(password),tenant_id=VALUES(tenant_id),name=VALUES(name),email=VALUES(email),role=VALUES(role),enabled=1;
