-- Generated: users (sfa_central.app_user) + full profiles (tenant employee), linked by emp_id

USE sfa_demo;
INSERT INTO designation (oid,designation_code,designation_name,status) VALUES
 (1,'DESIG-ADM','Administrator','Y'),(2,'DESIG-AM','Area Manager','Y'),(3,'DESIG-MR','Medical Representative','Y')
 ON DUPLICATE KEY UPDATE designation_name=VALUES(designation_name),status='Y';
INSERT INTO district (oid,district_code,district_name,state_oid,status) VALUES
 (1,'DIST-MUM','Mumbai',1,'Y'),(2,'DIST-PUN','Pune',1,'Y')
 ON DUPLICATE KEY UPDATE district_name=VALUES(district_name),state_oid=VALUES(state_oid),status='Y';
INSERT INTO employee (emp_id,emp_name,username,password_hash,designation_oid,emp_level,mobile,email,state_oid,district_oid,dob,status) VALUES ('DEMO-ADMIN','Demo Admin','demo_admin','',1,9,'9000000096','admin@demo.com',1,1,'1980-05-10','Y') ON DUPLICATE KEY UPDATE emp_name=VALUES(emp_name),designation_oid=VALUES(designation_oid),emp_level=VALUES(emp_level),mobile=VALUES(mobile),email=VALUES(email),state_oid=VALUES(state_oid),district_oid=VALUES(district_oid),dob=VALUES(dob),status='Y';
INSERT INTO sfa_central.app_user (username,password,tenant_id,enabled,role,emp_id) VALUES ('demo_admin','$2y$10$3GZCivV78xwReZb4nnzATuQZHwo2fT2nocs46kjmkd1Baaubm0KWS','demo',1,'ADMIN','DEMO-ADMIN') ON DUPLICATE KEY UPDATE password=VALUES(password),tenant_id=VALUES(tenant_id),role=VALUES(role),emp_id=VALUES(emp_id),enabled=1;
INSERT INTO employee (emp_id,emp_name,username,password_hash,designation_oid,emp_level,mobile,email,state_oid,district_oid,dob,status) VALUES ('DEMO-MGR','Demo Manager','demo_mgr','',2,5,'9000000091','mgr@demo.com',1,1,'1985-08-15','Y') ON DUPLICATE KEY UPDATE emp_name=VALUES(emp_name),designation_oid=VALUES(designation_oid),emp_level=VALUES(emp_level),mobile=VALUES(mobile),email=VALUES(email),state_oid=VALUES(state_oid),district_oid=VALUES(district_oid),dob=VALUES(dob),status='Y';
INSERT INTO sfa_central.app_user (username,password,tenant_id,enabled,role,emp_id) VALUES ('demo_mgr','$2y$10$uwiotUG8fxQqSTt1oP3F..d6ckpPWgRRRQVLgKVOvLWHY5fCieMRG','demo',1,'MANAGER','DEMO-MGR') ON DUPLICATE KEY UPDATE password=VALUES(password),tenant_id=VALUES(tenant_id),role=VALUES(role),emp_id=VALUES(emp_id),enabled=1;
INSERT INTO employee (emp_id,emp_name,username,password_hash,designation_oid,emp_level,mobile,email,state_oid,district_oid,dob,status) VALUES ('DEMO-REP1','Demo Rep 1','demo_rep1','',3,1,'9000000086','rep1@demo.com',1,2,'1992-03-22','Y') ON DUPLICATE KEY UPDATE emp_name=VALUES(emp_name),designation_oid=VALUES(designation_oid),emp_level=VALUES(emp_level),mobile=VALUES(mobile),email=VALUES(email),state_oid=VALUES(state_oid),district_oid=VALUES(district_oid),dob=VALUES(dob),status='Y';
INSERT INTO sfa_central.app_user (username,password,tenant_id,enabled,role,emp_id) VALUES ('demo_rep1','$2y$10$5BhJA557omkDN6L8IT0wBu8qmQsG1WGt5zGb4bw83q3J1riHX/UzK','demo',1,'USER','DEMO-REP1') ON DUPLICATE KEY UPDATE password=VALUES(password),tenant_id=VALUES(tenant_id),role=VALUES(role),emp_id=VALUES(emp_id),enabled=1;
INSERT INTO employee (emp_id,emp_name,username,password_hash,designation_oid,emp_level,mobile,email,state_oid,district_oid,dob,status) VALUES ('DEMO-REP2','Demo Rep 2','demo_rep2','',3,1,'9000000069','rep2@demo.com',1,2,'1994-11-05','Y') ON DUPLICATE KEY UPDATE emp_name=VALUES(emp_name),designation_oid=VALUES(designation_oid),emp_level=VALUES(emp_level),mobile=VALUES(mobile),email=VALUES(email),state_oid=VALUES(state_oid),district_oid=VALUES(district_oid),dob=VALUES(dob),status='Y';
INSERT INTO sfa_central.app_user (username,password,tenant_id,enabled,role,emp_id) VALUES ('demo_rep2','$2y$10$7xJytVUSekb9FpwymCL3nOMaShWoQDyAbyQUz/oXXipAsVy6dmT/6','demo',1,'USER','DEMO-REP2') ON DUPLICATE KEY UPDATE password=VALUES(password),tenant_id=VALUES(tenant_id),role=VALUES(role),emp_id=VALUES(emp_id),enabled=1;

USE acme_db;
INSERT INTO designation (oid,designation_code,designation_name,status) VALUES
 (1,'DESIG-ADM','Administrator','Y'),(2,'DESIG-AM','Area Manager','Y'),(3,'DESIG-MR','Medical Representative','Y')
 ON DUPLICATE KEY UPDATE designation_name=VALUES(designation_name),status='Y';
INSERT INTO district (oid,district_code,district_name,state_oid,status) VALUES
 (1,'DIST-AHM','Ahmedabad',1,'Y'),(2,'DIST-SUR','Surat',1,'Y')
 ON DUPLICATE KEY UPDATE district_name=VALUES(district_name),state_oid=VALUES(state_oid),status='Y';
INSERT INTO employee (emp_id,emp_name,username,password_hash,designation_oid,emp_level,mobile,email,state_oid,district_oid,dob,status) VALUES ('ACME-ADMIN','Acme Admin','acme_admin','',1,9,'9000000059','admin@acme.com',1,1,'1980-05-10','Y') ON DUPLICATE KEY UPDATE emp_name=VALUES(emp_name),designation_oid=VALUES(designation_oid),emp_level=VALUES(emp_level),mobile=VALUES(mobile),email=VALUES(email),state_oid=VALUES(state_oid),district_oid=VALUES(district_oid),dob=VALUES(dob),status='Y';
INSERT INTO sfa_central.app_user (username,password,tenant_id,enabled,role,emp_id) VALUES ('acme_admin','$2y$10$DJfE6yNyNpYEzefFI1X3belHfrZTwZI8acUKs0Y82zV7QX.cDAVhy','acme',1,'ADMIN','ACME-ADMIN') ON DUPLICATE KEY UPDATE password=VALUES(password),tenant_id=VALUES(tenant_id),role=VALUES(role),emp_id=VALUES(emp_id),enabled=1;
INSERT INTO employee (emp_id,emp_name,username,password_hash,designation_oid,emp_level,mobile,email,state_oid,district_oid,dob,status) VALUES ('ACME-MGR','Acme Manager','acme_mgr','',2,5,'9000000087','mgr@acme.com',1,1,'1985-08-15','Y') ON DUPLICATE KEY UPDATE emp_name=VALUES(emp_name),designation_oid=VALUES(designation_oid),emp_level=VALUES(emp_level),mobile=VALUES(mobile),email=VALUES(email),state_oid=VALUES(state_oid),district_oid=VALUES(district_oid),dob=VALUES(dob),status='Y';
INSERT INTO sfa_central.app_user (username,password,tenant_id,enabled,role,emp_id) VALUES ('acme_mgr','$2y$10$eVCIDOn7QttiAwzEa0s13.w0TSjcrFokdw8S7TbOmidbHSvjMmeaa','acme',1,'MANAGER','ACME-MGR') ON DUPLICATE KEY UPDATE password=VALUES(password),tenant_id=VALUES(tenant_id),role=VALUES(role),emp_id=VALUES(emp_id),enabled=1;
INSERT INTO employee (emp_id,emp_name,username,password_hash,designation_oid,emp_level,mobile,email,state_oid,district_oid,dob,status) VALUES ('ACME-REP1','Acme Rep 1','acme_rep1','',3,1,'9000000038','rep1@acme.com',1,2,'1992-03-22','Y') ON DUPLICATE KEY UPDATE emp_name=VALUES(emp_name),designation_oid=VALUES(designation_oid),emp_level=VALUES(emp_level),mobile=VALUES(mobile),email=VALUES(email),state_oid=VALUES(state_oid),district_oid=VALUES(district_oid),dob=VALUES(dob),status='Y';
INSERT INTO sfa_central.app_user (username,password,tenant_id,enabled,role,emp_id) VALUES ('acme_rep1','$2y$10$e4MKyOQ0jDw86RJoY2uR9uagL0jMLh2aXdePisUDi8Diu9sOJ6BbK','acme',1,'USER','ACME-REP1') ON DUPLICATE KEY UPDATE password=VALUES(password),tenant_id=VALUES(tenant_id),role=VALUES(role),emp_id=VALUES(emp_id),enabled=1;
INSERT INTO employee (emp_id,emp_name,username,password_hash,designation_oid,emp_level,mobile,email,state_oid,district_oid,dob,status) VALUES ('ACME-REP2','Acme Rep 2','acme_rep2','',3,1,'9000000061','rep2@acme.com',1,2,'1994-11-05','Y') ON DUPLICATE KEY UPDATE emp_name=VALUES(emp_name),designation_oid=VALUES(designation_oid),emp_level=VALUES(emp_level),mobile=VALUES(mobile),email=VALUES(email),state_oid=VALUES(state_oid),district_oid=VALUES(district_oid),dob=VALUES(dob),status='Y';
INSERT INTO sfa_central.app_user (username,password,tenant_id,enabled,role,emp_id) VALUES ('acme_rep2','$2y$10$jt/k/x2NVrk05SjLXCm7Ze8ARG8WvdjA7OKauWgWFM4Tu2FzyK0nG','acme',1,'USER','ACME-REP2') ON DUPLICATE KEY UPDATE password=VALUES(password),tenant_id=VALUES(tenant_id),role=VALUES(role),emp_id=VALUES(emp_id),enabled=1;

USE globex_db;
INSERT INTO designation (oid,designation_code,designation_name,status) VALUES
 (1,'DESIG-ADM','Administrator','Y'),(2,'DESIG-AM','Area Manager','Y'),(3,'DESIG-MR','Medical Representative','Y')
 ON DUPLICATE KEY UPDATE designation_name=VALUES(designation_name),status='Y';
INSERT INTO district (oid,district_code,district_name,state_oid,status) VALUES
 (1,'DIST-BLR','Bangalore Urban',1,'Y'),(2,'DIST-MYS','Mysuru',1,'Y')
 ON DUPLICATE KEY UPDATE district_name=VALUES(district_name),state_oid=VALUES(state_oid),status='Y';
INSERT INTO employee (emp_id,emp_name,username,password_hash,designation_oid,emp_level,mobile,email,state_oid,district_oid,dob,status) VALUES ('GLOBEX-ADMIN','Globex Admin','globex_admin','',1,9,'9000000099','admin@globex.com',1,1,'1980-05-10','Y') ON DUPLICATE KEY UPDATE emp_name=VALUES(emp_name),designation_oid=VALUES(designation_oid),emp_level=VALUES(emp_level),mobile=VALUES(mobile),email=VALUES(email),state_oid=VALUES(state_oid),district_oid=VALUES(district_oid),dob=VALUES(dob),status='Y';
INSERT INTO sfa_central.app_user (username,password,tenant_id,enabled,role,emp_id) VALUES ('globex_admin','$2y$10$YQ3xy/xJQBU5RDg0miYQEO95OSY4i82z0nUBhF6kbJeFbcppK2H/i','globex',1,'ADMIN','GLOBEX-ADMIN') ON DUPLICATE KEY UPDATE password=VALUES(password),tenant_id=VALUES(tenant_id),role=VALUES(role),emp_id=VALUES(emp_id),enabled=1;
INSERT INTO employee (emp_id,emp_name,username,password_hash,designation_oid,emp_level,mobile,email,state_oid,district_oid,dob,status) VALUES ('GLOBEX-MGR','Globex Manager','globex_mgr','',2,5,'9000000031','mgr@globex.com',1,1,'1985-08-15','Y') ON DUPLICATE KEY UPDATE emp_name=VALUES(emp_name),designation_oid=VALUES(designation_oid),emp_level=VALUES(emp_level),mobile=VALUES(mobile),email=VALUES(email),state_oid=VALUES(state_oid),district_oid=VALUES(district_oid),dob=VALUES(dob),status='Y';
INSERT INTO sfa_central.app_user (username,password,tenant_id,enabled,role,emp_id) VALUES ('globex_mgr','$2y$10$xTUoIYUjxIq4HEkLcNnnSO23U854/Bm7/oeVapMRme06XPksPwFRO','globex',1,'MANAGER','GLOBEX-MGR') ON DUPLICATE KEY UPDATE password=VALUES(password),tenant_id=VALUES(tenant_id),role=VALUES(role),emp_id=VALUES(emp_id),enabled=1;
INSERT INTO employee (emp_id,emp_name,username,password_hash,designation_oid,emp_level,mobile,email,state_oid,district_oid,dob,status) VALUES ('GLOBEX-REP1','Globex Rep 1','globex_rep1','',3,1,'9000000042','rep1@globex.com',1,2,'1992-03-22','Y') ON DUPLICATE KEY UPDATE emp_name=VALUES(emp_name),designation_oid=VALUES(designation_oid),emp_level=VALUES(emp_level),mobile=VALUES(mobile),email=VALUES(email),state_oid=VALUES(state_oid),district_oid=VALUES(district_oid),dob=VALUES(dob),status='Y';
INSERT INTO sfa_central.app_user (username,password,tenant_id,enabled,role,emp_id) VALUES ('globex_rep1','$2y$10$Wc5Hu5TpH10ORr1uDvUZUODp2t7x65vJiyjRiplTgIrqCp/.ocVxu','globex',1,'USER','GLOBEX-REP1') ON DUPLICATE KEY UPDATE password=VALUES(password),tenant_id=VALUES(tenant_id),role=VALUES(role),emp_id=VALUES(emp_id),enabled=1;
INSERT INTO employee (emp_id,emp_name,username,password_hash,designation_oid,emp_level,mobile,email,state_oid,district_oid,dob,status) VALUES ('GLOBEX-REP2','Globex Rep 2','globex_rep2','',3,1,'9000000076','rep2@globex.com',1,2,'1994-11-05','Y') ON DUPLICATE KEY UPDATE emp_name=VALUES(emp_name),designation_oid=VALUES(designation_oid),emp_level=VALUES(emp_level),mobile=VALUES(mobile),email=VALUES(email),state_oid=VALUES(state_oid),district_oid=VALUES(district_oid),dob=VALUES(dob),status='Y';
INSERT INTO sfa_central.app_user (username,password,tenant_id,enabled,role,emp_id) VALUES ('globex_rep2','$2y$10$31qrITGuYKj/MwcccILewenWbZg7E.K638tvn9aa0o835OF0uQ.s2','globex',1,'USER','GLOBEX-REP2') ON DUPLICATE KEY UPDATE password=VALUES(password),tenant_id=VALUES(tenant_id),role=VALUES(role),emp_id=VALUES(emp_id),enabled=1;

USE initech_db;
INSERT INTO designation (oid,designation_code,designation_name,status) VALUES
 (1,'DESIG-ADM','Administrator','Y'),(2,'DESIG-AM','Area Manager','Y'),(3,'DESIG-MR','Medical Representative','Y')
 ON DUPLICATE KEY UPDATE designation_name=VALUES(designation_name),status='Y';
INSERT INTO district (oid,district_code,district_name,state_oid,status) VALUES
 (1,'DIST-ND','New Delhi',1,'Y'),(2,'DIST-SD','South Delhi',1,'Y')
 ON DUPLICATE KEY UPDATE district_name=VALUES(district_name),state_oid=VALUES(state_oid),status='Y';
INSERT INTO employee (emp_id,emp_name,username,password_hash,designation_oid,emp_level,mobile,email,state_oid,district_oid,dob,status) VALUES ('INITECH-ADMIN','Initech Admin','initech_admin','',1,9,'9000000025','admin@initech.com',1,1,'1980-05-10','Y') ON DUPLICATE KEY UPDATE emp_name=VALUES(emp_name),designation_oid=VALUES(designation_oid),emp_level=VALUES(emp_level),mobile=VALUES(mobile),email=VALUES(email),state_oid=VALUES(state_oid),district_oid=VALUES(district_oid),dob=VALUES(dob),status='Y';
INSERT INTO sfa_central.app_user (username,password,tenant_id,enabled,role,emp_id) VALUES ('initech_admin','$2y$10$v05oZDxk.kdnYSEeD2KQ3OFC/Jb0E3oUMsrgx3PbdZmJ97HtSmO0C','initech',1,'ADMIN','INITECH-ADMIN') ON DUPLICATE KEY UPDATE password=VALUES(password),tenant_id=VALUES(tenant_id),role=VALUES(role),emp_id=VALUES(emp_id),enabled=1;
INSERT INTO employee (emp_id,emp_name,username,password_hash,designation_oid,emp_level,mobile,email,state_oid,district_oid,dob,status) VALUES ('INITECH-MGR','Initech Manager','initech_mgr','',2,5,'9000000087','mgr@initech.com',1,1,'1985-08-15','Y') ON DUPLICATE KEY UPDATE emp_name=VALUES(emp_name),designation_oid=VALUES(designation_oid),emp_level=VALUES(emp_level),mobile=VALUES(mobile),email=VALUES(email),state_oid=VALUES(state_oid),district_oid=VALUES(district_oid),dob=VALUES(dob),status='Y';
INSERT INTO sfa_central.app_user (username,password,tenant_id,enabled,role,emp_id) VALUES ('initech_mgr','$2y$10$chaba5eiUph0/f51pMMKMOMuFZ3i6mqD/XpIqchYiDbNSLouHyXzK','initech',1,'MANAGER','INITECH-MGR') ON DUPLICATE KEY UPDATE password=VALUES(password),tenant_id=VALUES(tenant_id),role=VALUES(role),emp_id=VALUES(emp_id),enabled=1;
INSERT INTO employee (emp_id,emp_name,username,password_hash,designation_oid,emp_level,mobile,email,state_oid,district_oid,dob,status) VALUES ('INITECH-REP1','Initech Rep 1','initech_rep1','',3,1,'9000000049','rep1@initech.com',1,2,'1992-03-22','Y') ON DUPLICATE KEY UPDATE emp_name=VALUES(emp_name),designation_oid=VALUES(designation_oid),emp_level=VALUES(emp_level),mobile=VALUES(mobile),email=VALUES(email),state_oid=VALUES(state_oid),district_oid=VALUES(district_oid),dob=VALUES(dob),status='Y';
INSERT INTO sfa_central.app_user (username,password,tenant_id,enabled,role,emp_id) VALUES ('initech_rep1','$2y$10$uRmeu.kFJy4OyFP7jv1h3uwUCA7U0gata2bCLINdGdXTXzzF//1n.','initech',1,'USER','INITECH-REP1') ON DUPLICATE KEY UPDATE password=VALUES(password),tenant_id=VALUES(tenant_id),role=VALUES(role),emp_id=VALUES(emp_id),enabled=1;
INSERT INTO employee (emp_id,emp_name,username,password_hash,designation_oid,emp_level,mobile,email,state_oid,district_oid,dob,status) VALUES ('INITECH-REP2','Initech Rep 2','initech_rep2','',3,1,'9000000089','rep2@initech.com',1,2,'1994-11-05','Y') ON DUPLICATE KEY UPDATE emp_name=VALUES(emp_name),designation_oid=VALUES(designation_oid),emp_level=VALUES(emp_level),mobile=VALUES(mobile),email=VALUES(email),state_oid=VALUES(state_oid),district_oid=VALUES(district_oid),dob=VALUES(dob),status='Y';
INSERT INTO sfa_central.app_user (username,password,tenant_id,enabled,role,emp_id) VALUES ('initech_rep2','$2y$10$sbiDRC6PypUCDaFxI2ZVpuyv/drQR4GrryhGEiLDgbq6iBbk6xPGK','initech',1,'USER','INITECH-REP2') ON DUPLICATE KEY UPDATE password=VALUES(password),tenant_id=VALUES(tenant_id),role=VALUES(role),emp_id=VALUES(emp_id),enabled=1;
